# Generated by Django 4.1.1 on 2022-10-25 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='recipe',
            managers=[
            ],
        ),
    ]
