# Generated by Django 4.1.1 on 2022-10-25 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='preparation_steps_is_html',
            new_name='are_the_preparation_steps_html',
        ),
    ]
